// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwl5HCRsJgnabyHrBdIfu9iK8ll01CeKI',
    appId: '1:381489634289:web:28214546e25f91cc2fc250',
    messagingSenderId: '381489634289',
    projectId: 'learninga-9d560',
    authDomain: 'learninga-9d560.firebaseapp.com',
    storageBucket: 'learninga-9d560.firebasestorage.app',
    measurementId: 'G-9VMG92GGXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRxJvDW50WKwgjzPeu23xRhariscpcKMU',
    appId: '1:381489634289:android:6f45097d9cd342412fc250',
    messagingSenderId: '381489634289',
    projectId: 'learninga-9d560',
    storageBucket: 'learninga-9d560.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRLs7QdpZTPAGXCxzICKga6aD_fgGab0s',
    appId: '1:381489634289:ios:d75d7337f32d2c972fc250',
    messagingSenderId: '381489634289',
    projectId: 'learninga-9d560',
    storageBucket: 'learninga-9d560.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );
}
